# Generated by Django 6.0.3 on 2026-03-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='SaldoCuentaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta')),
            ],
            options={
                'unique_together': {('cuenta', 'anio', 'mes')},
            },
        ),
    ]
