# Generated by Django 6.0.3 on 2026-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('CAJA', 'Caja'), ('FISCAL', 'Fiscal')], max_length=10)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('UYU', 'UYU')], max_length=3)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
