# Generated by Django 6.0.3 on 2026-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_resultado', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('NEUTRO', 'Neutro')], max_length=10)),
                ('afecta_banco', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
