# Generated by Django 6.0.3 on 2026-03-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.movimiento')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rubros.rubro')),
            ],
        ),
    ]
