# Generated by Django 6.0.3 on 2026-03-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('rubros', '0002_movimientorubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientorubro',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='requiere_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
