# Generated by Django 6.0.3 on 2026-03-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('UYU', 'UYU')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACREDITADO', 'Acreditado')], default='PENDIENTE', max_length=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta')),
            ],
        ),
    ]
